### PR TITLE
Implement RDF Patch serializer

### PR DESCRIPTION
**Pull request by recalcitrantsupplant**
Supports serialization from Dataset instances only; triples and quads within a Dataset are supported.

# Summary of changes

Three methods to create RDF Patches from RDFLib Datasets:
1. Serialize a Dataset as an addition patch
2. Serialize a Dataset as a delete patch
3. Create a patch representing the difference between a Dataset instance and a target Dataset instance

Basic usage:
1. `ds.serialize(format="patch", operation="add")`
2. `ds.serialize(format="patch", operation="remove")`
3. `ds1.serialize(format="patch", target=ds2)`

Complete examples are provided in an example script.

# Checklist

- [x] Checked that there aren't other open pull requests for
  the same change.
- [x] Checked that all tests and type checking passes.
- If the change adds new features or changes the RDFLib public API:
  - [x] ~Created an issue to discuss the change and get in-principle agreement.~ Discussed w/ maintainers
  - [x] Considered adding an example in `./examples`.
- If the change has a potential impact on users of this project:
  - [x] Updated relevant documentation to avoid inaccuracies.
  - [x] Considered adding additional documentation.
- [x] Considered granting [push permissions to the PR branch](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork),
  so maintainers can fix minor issues and keep your PR up to date.

### CODE REVIEW

**Review by edmondchuc — COMMENTED** [review]
As discussed in our chat, this version of the serializer could function as a utility function rather than a serializer, performing one of two operations:

- Add or Remove Operation: Takes a dataset with an `add` or `remove` operation parameter and generates an RDF patch.

- Difference Operation: Takes two datasets and performs a `difference` operation, with the second dataset as the "target".

This approach allows us to reserve the patch serializer for RDF patches on an RDFLib store with change tracking enabled. The backend would track changes applied to the store through a series of RDF patches, and the serializer would output these patches sequentially.

I'm not suggesting we need to implement this, but just toying with what the potential RDFLib public interfaces may look like with a complete RDF patch support.

File: rdflib/plugins/serializers/patch.py [hunk 1]
```diff
@@ -0,0 +1,95 @@
...
+        if base is not None:
+            warnings.warn("PatchSerializer does not support base.")
+        if encoding is not None and encoding.lower() != self.encoding.lower():
+            warnings.warn(
+                "PatchSerializer does not use custom encoding. "
+                f"Given encoding was: {encoding}"
+            )
+
+        def write_header():
+            stream.write(f"H id <{header_id}> .\n".encode(encoding, "replace"))
```
[the remark this answers is not in the document]
Comment (recalcitrantsupplant) [reply rdflib/plugins/serializers/patch.py:52]: It's consistent with the jsonld, nquads, and rdf xml serializers. I would think the default behaviour on encode would be better: `The default is 'strict' meaning that encoding errors raise a UnicodeEncodeError`. It would be good to know if there was a specific reason for the use of "replace" - @nicholascar @ashleysommer coincidentally you're on the commits for those serializers (a few years ago, I realise) - you wouldn't happen to recall or know why "replace" was used?

[the remark this answers is not in the document]
Comment (ashleysommer) [reply rdflib/plugins/serializers/patch.py:52]: I don't remember the exact reason. There was a bunch of stuff messed up and in a broken state after the python2->python3 `unicode`->`str` migration, I believe the solution was to pepper a bunch of ".encode()" method calls everywhere required, but we didn't want that to start causing code to break that was previously working, so using "replace" was a way of silently fixing it.
I agree however it is the wrong solution.
I've been doing some background work on bringing up the standard of the `stream` interface used by parsers and serializers, its another part that needs a big breaking change to fix, as part of RDFLib8.

**Comment by ashleysommer** [comment]
The mypy issues in `main` should be resolved now. I've resynced this PR, hopefully it parses now.

**Comment by ashleysommer** [comment]
@recalcitrantsupplant 
Still 4 mypy errors related to this PR:
```
poetry run python -m mypy --show-error-context --show-error-codes --junit-xml=test_reports/3.9-macos-latest-mypy-junit.xml
  rdflib/plugins/serializers/patch.py: note: In member "serialize" of class "PatchSerializer":
  rdflib/plugins/serializers/patch.py:30: error: Signature of "serialize" incompatible with supertype "Serializer"  [override]
  rdflib/plugins/serializers/patch.py:30: note:      Superclass:
  rdflib/plugins/serializers/patch.py:30: note:          def serialize(self, stream: IO[bytes], base: Optional[str] = ..., encoding: Optional[str] = ..., **args: Any) -> None
  rdflib/plugins/serializers/patch.py:30: note:      Subclass:
  rdflib/plugins/serializers/patch.py:30: note:          def serialize(self, stream: IO[bytes], base: Optional[str] = ..., encoding: Optional[str] = ..., operation: Optional[str] = ..., target: Optional[Graph] = ..., header_id: Optional[str] = ..., header_prev: Optional[str] = ...) -> Any
  rdflib/plugins/serializers/patch.py: note: In function "serialize":
  rdflib/plugins/serializers/patch.py:60: error: "Graph" has no attribute "get_context"  [attr-defined]
  rdflib/plugins/serializers/patch.py: note: In member "serialize" of class "PatchSerializer":
  rdflib/plugins/serializers/patch.py:74: error: "Graph" has no attribute "contexts"  [attr-defined]
  rdflib/plugins/serializers/patch.py: note: In member "_patch_row" of class "PatchSerializer":
  rdflib/plugins/serializers/patch.py:88: error: "Graph" has no attribute "default_context"  [attr-defined]
  Found 4 errors in 1 file (checked 401 source files)
```

File: rdflib/plugins/serializers/patch.py (hunk 1 above)
[the remark this answers is not in the document]
Comment (recalcitrantsupplant) [reply rdflib/plugins/serializers/patch.py:66]: Discussed w/ Ashley  & Nick leaving making any encoding changes in a separate PR to generally address the issue.

**Comment by ashleysommer** [comment]
@recalcitrantsupplant I thought this was complete and passing tests and ready to merge, however after merging it there are now some test failures appearing in `main`, and I've verified locally it has something to do with the roundtrip tests.
As this `.patch` parser is a registered RDFLib parser plugin, the test suite includes it in the roundtrip tests. There are a bunch of `.nt`->`.patch` conversions and `.n3`->`.patch` roundtrip tests that are failing with odd errors.
I don't have time to troubleshoot it now.

As @edmondchuc mentioned above, I don't know what use this is as a regular RDFLib serializer, because you really need to associate it with actions such as `Add` or `Remove` or `Difference`, which are not defined by default when doing operations like roundtrip. This really makes sense as a helper function, that allows you to script the creation of a `.patch` file.

To allow `main` to pass tests again, I'm going to revert this merge. We can revisit it again soon.

**Comment by ashleysommer** [comment]
@recalcitrantsupplant  Another update, I haven't revered this yet.
I found that if I add a fallback to find cases where `operation` is not passed, but `target` is also not passed, then default to `add` operation. With simple change, now all roundtrip tests are passing. Does that sound like a sensible change to you? I would assume anyone tring to naively serialize a graph or Dataset to `.patch` format without an operation is going to by default want the `add` patch operation.

**Comment by ashleysommer** [comment]
The issue described in the previous two comments is now fixed by #2898 so tests in `main` are now passing.
