### ISSUE TITLE
Error bundling with py2exe when upgrading from 3.X to 4.X 

### ISSUE THREAD

**Issue by Prev-I** [RDFLib/rdflib#826]
We are trying to migrate from rdflib 3.2.3 to latest versions.
When we use our app launching directly with python everything works fine, but when we freeze and build the exe with esky and py2exe we got this error on launch.

The enviroment is the following:
```
python 2.7.14-win32
rdflib==4.2.2
py2exe-py2==0.6.9
esky==0.7.4
```
this is the error stacktrace:
```
Traceback (most recent call last):
  File "__main__.py", line 555, in <module>
  File "__main__.py", line 120, in bootstrap
  File "__main__.py", line 144, in chainload
  File "__main__.py", line 551, in _chainload
  File "myapp.pyw", line 26, in <module>
  File "zipextimporter.pyc", line 82, in load_module
  File "rdflib\__init__.pyc", line 78, in <module>
AttributeError: 'Blackhole' object has no attribute 'isatty'
```

I've got no idea where to look for the 'Blackhole' object...
